### ISSUE TITLE
Error: Could not import "'gligen_gui".

### ISSUE THREAD

**Issue by Axolet** [mut-ex/gligen-gui#1]
Followed the steps exactly, but when running the code
`flask --app 'gligen_gui:create_app(8188)' run --port 50001`

It gives me the following error
`Error: Could not import "'gligen_gui".`

**Comment by pointermess** [comment]
I have the same issue:

```
I:\99_AIModels\StableDiffusion\gligen-gui>flask --app 'gligen_gui:create_app(8188)' run --port 5000
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: Could not import "'gligen_gui".
```

**Comment by JoeySalmons** [comment]
Use double quotes instead:
`flask --app "gligen_gui:create_app(8188)" run --port 50001`

Same error for me, but the double quotes made it work.

**Comment by Axolet** [comment]
Thank you, it works!
