### ISSUE TITLE
VAE selector

### ISSUE THREAD

**Issue by sophosympatheia** [mut-ex/gligen-gui#21]
First let me say this is a great tool. I like how you've kept it simple too.

Can you add a GUI element for selecting a VAE to use with the currently loaded model? I know many models come with the VAE baked in these days, but not all of them, so it would be handy to specify one to load.

Thanks again for making this great tool.

**Comment by Wraithnaut** [comment]
Fellow gligen-gui user here, this feature was added recently along with some other features.

https://github.com/mut-ex/gligen-gui/blob/main/latest.png

**Comment by sophosympatheia** [comment]
Much thanks! :)
