### ISSUE TITLE
No Checkpoint, No VAE, No Lora loaded

### ISSUE THREAD

**Issue by Mimicgod** [mut-ex/gligen-gui#37]
I used the portable version of ComfyUI running on port 8188 and everything is working fine.
However after following all the steps in the Gligen GUI instruction, I see no checkpoint, no lora loaded in the GUI.
![Untitled](https://github.com/mut-ex/gligen-gui/assets/78788093/75524bb2-f51c-421c-b143-86cc5b797a6d)
I can't do anything.

Here's the log:
Go to: http://127.0.0.1:5000/port/8188
 * Serving Flask app 'gligen_gui:create_app(8188)'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
8188
127.0.0.1 - - [28/Feb/2024 21:06:28] "GET /port/8188 HTTP/1.1" 200 -
127.0.0.1 - - [28/Feb/2024 21:06:28] "GET /static/images/background-mode.svg HTTP/1.1" 304 -
127.0.0.1 - - [28/Feb/2024 21:06:28] "GET /static/images/wallpaper.svg HTTP/1.1" 304 -
127.0.0.1 - - [28/Feb/2024 21:06:28] "GET /static/style.css HTTP/1.1" 304 -
127.0.0.1 - - [28/Feb/2024 21:06:28] "GET /static/toast.css HTTP/1.1" 304 -
127.0.0.1 - - [28/Feb/2024 21:06:28] "GET /static/js/whiteboard/main.js HTTP/1.1" 304 -
127.0.0.1 - - [28/Feb/2024 21:06:28] "GET /static/images/download-image.svg HTTP/1.1" 304 -
127.0.0.1 - - [28/Feb/2024 21:06:28] "GET /static/images/information.svg HTTP/1.1" 304 -
127.0.0.1 - - [28/Feb/2024 21:06:28] "GET /static/images/dice.svg HTTP/1.1" 304 -
127.0.0.1 - - [28/Feb/2024 21:06:28] "GET /static/js/whiteboard/artist.js HTTP/1.1" 304 -
127.0.0.1 - - [28/Feb/2024 21:06:28] "GET /static/js/whiteboard/shape.js HTTP/1.1" 304 -
127.0.0.1 - - [28/Feb/2024 21:06:28] "GET /static/js/whiteboard/rectangle.js HTTP/1.1" 304 -
127.0.0.1 - - [28/Feb/2024 21:06:28] "GET /static/js/whiteboard/surface.js HTTP/1.1" 304 -
127.0.0.1 - - [28/Feb/2024 21:06:28] "GET /static/js/utils.js HTTP/1.1" 304 -
127.0.0.1 - - [28/Feb/2024 21:06:28] "GET /static/js/loaders.js HTTP/1.1" 304 -
127.0.0.1 - - [28/Feb/2024 21:06:28] "GET /static/js/nodes.js HTTP/1.1" 304 -
127.0.0.1 - - [28/Feb/2024 21:06:28] "GET /static/js/draw.js HTTP/1.1" 304 -
127.0.0.1 - - [28/Feb/2024 21:06:28] "GET /static/js/toast.js HTTP/1.1" 304 -
127.0.0.1 - - [28/Feb/2024 21:06:28] "GET /static/js/extra.js HTTP/1.1" 304 -
127.0.0.1 - - [28/Feb/2024 21:06:28] "GET /static/js/main.js HTTP/1.1" 304 -
127.0.0.1 - - [28/Feb/2024 21:06:28] "GET /static/images/recycle.svg HTTP/1.1" 304 -
127.0.0.1 - - [28/Feb/2024 21:06:28] "GET /static/images/add.svg HTTP/1.1" 304 -
127.0.0.1 - - [28/Feb/2024 21:06:28] "GET /static/images/eraser.svg HTTP/1.1" 304 -
127.0.0.1 - - [28/Feb/2024 21:06:28] "GET /static/images/file-save.svg HTTP/1.1" 304 -
127.0.0.1 - - [28/Feb/2024 21:06:28] "GET /static/images/open.svg HTTP/1.1" 304 -

**Comment by hobojoker** [comment]
Same issue, although I'm not using the portable version

**Comment by hobojoker** [comment]
> Can you share what you see in the browser dev console? >

GlobalState instantiated
main.js:319 undefined undefined
surface.js:152 in resize
main.js:324 ComfyUI port =  8188
main.js:139 Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at postInputArgs (main.js:139:55)
    at Proxy.saveToLocalStorage (extra.js:98:5)
    at updateSeedModeIcons (loaders.js:16:17)
    at loadSeed (loaders.js:19:3)
    at main.js:326:3

**Comment by mut-ex** [comment]
Can you try the latest commit? It should hopefully fix this.

**Comment by Mimicgod** [comment]
> Can you try the latest commit? It should hopefully fix this.

thank you so much. The issue is fixed. Great works!
