### ISSUE TITLE
Prompt successfully queued but no images being displayed

### ISSUE THREAD

**Issue by athenas-lab** [mut-ex/gligen-gui#44]
Hi,

Thank you for making your GUI available. I installed the gligen-gui as per the instructions and tried to create a couple of images. I have the comfyUI running on one tab and the gligen-gui running on a different tab on port 5000.  The prompt is successfully queued, but no images are being displayed in the gui.  I tried both the v1-5-pruned.ckpt and v1-5-pruned-emaonly.ckpt but neither of them generated the images.  I am not using any LORAs or VAE. The graphic below shows my session. I would appreciate any help. 

Thanks

![Screenshot from 2024-06-08 20-37-02](https://github.com/mut-ex/gligen-gui/assets/12867837/81a57f68-ab50-48a9-877c-c4bf30f9490f)

**Comment by mut-ex** [comment]
Can you include what’s the output in the ComfyUI terminal window? Also, do you see the generated images in the ComfyUI output directory?On 8 Jun 2024, at 10:54 pm, athena913 ***@***.***> wrote:﻿
Hi,
Thank you for making your GUI available. I installed the gligen-gui as per the instructions and tried to create a couple of images. I have the comfyUI running on one tab and the gligen-gui running on a different tab on port 5000.  The prompt is successfully queued, but no images are being displayed in the gui.  I tried both the v1-5-pruned.ckpt and v1-5-pruned-emaonly.ckpt but neither of them generated the images. The graphic below shows my session. I would appreciate any help.
Thanks
Screenshot.from.2024-06-08.20-37-02.png (view on web)

**Comment by athenas-lab** [comment]
Thank you for your response. No images are output in the ComfyUI output folder.  There is a "Header too large" error from ComfyUI when loading the gligen model. I am using gligen_sd14_textbox_pruned.safetensors from huggingface as the gligen model. Do you know why I am getting this error?



Here's the console output on the Gligen-UI terminal: 

```
127.0.0.1 - - [08/Jun/2024 20:49:26] "GET /static/images/file-save.svg HTTP/1.1" 304 -
127.0.0.1 - - [08/Jun/2024 20:49:26] "GET /static/images/add.svg HTTP/1.1" 304 -
Get Object Info:  CheckpointLoaderSimple
Get Object Info:  VAELoader
Get Object Info:  LoraLoaderModelOnly
Get Object Info:  KSampler
127.0.0.1 - - [08/Jun/2024 20:49:26] "GET /object_info/CheckpointLoaderSimple HTTP/1.1" 200 -
127.0.0.1 - - [08/Jun/2024 20:49:26] "GET /object_info/VAELoader HTTP/1.1" 200 -
127.0.0.1 - - [08/Jun/2024 20:49:26] "GET /object_info/KSampler HTTP/1.1" 200 -
127.0.0.1 - - [08/Jun/2024 20:49:26] "GET /object_info/LoraLoaderModelOnly HTTP/1.1" 200 -
127.0.0.1 - - [08/Jun/2024 20:49:26] "GET /static/images/eye-on.svg HTTP/1.1" 304 -
127.0.0.1 - - [08/Jun/2024 20:49:26] "GET /static/images/delete.svg HTTP/1.1" 304 -
127.0.0.1 - - [08/Jun/2024 20:49:33] "POST /prompt HTTP/1.1" 200 -
127.0.0.1 - - [08/Jun/2024 20:49:36] "GET /history HTTP/1.1" 200 -

```

Here's the output on the ComfyUI terminal:

```
To see the GUI go to: http://127.0.0.1:8188
got prompt
model_type EPS
Using pytorch attention in VAE
Using pytorch attention in VAE
Requested to load SD1ClipModel
Loading 1 new model
!!! Exception during processing!!! Error while deserializing header: HeaderTooLarge
Traceback (most recent call last):
  File "/apps/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/ComfyUI/nodes.py", line 960, in load_gligen
    gligen = comfy.sd.load_gligen(gligen_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/ComfyUI/comfy/sd.py", line 413, in load_gligen
    data = comfy.utils.load_torch_file(ckpt_path, safe_load=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/ComfyUI/comfy/utils.py", line 14, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniconda3/envs/comfyui/lib/python3.11/site-packages/safetensors/torch.py", line 311, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge


```

**Comment by athenas-lab** [comment]
The issue has been resolved. The gligen model did not have the correct size. So I had to download it again. Thanks for your help.

However, the generated images do not conform to the prompts and dont have the same quality that is in the paper. I just used simple prompts like "tree", "river" etc. This may be an issue with the gligen model rather than the UI.
