### ISSUE TITLE
SDXL and Size

### ISSUE THREAD

**Issue by Tobe2d** [mut-ex/gligen-gui#7]
Is there a way to work with SDXL?
and how can I change the frame size?

Maybe a feature request?

**Comment by mut-ex** [comment]
The latest commit now features the ability to change the size of the canvas. However unfortunately unless the team behing GLIGEN add support for SDXL I can't do anything about that.
![latest](https://github.com/mut-ex/gligen-gui/assets/21265981/2022a655-da05-424a-ae44-159972d47f0a)

**Comment by VictorZakharov** [comment]
Reference:
- https://github.com/gligen/GLIGEN/issues/46

**Comment by mut-ex** [comment]
GLIGEN does not work with SDXL currently.The feature to resize the canvas is already ***@***.***> wrote:﻿
Reference:

gligen/GLIGEN#46
