### ISSUE TITLE
Value not in list: gligen_name

### ISSUE THREAD

**Issue by YanWittmann** [mut-ex/gligen-gui#8]
Hi there!

Using the latest ComfyUI and gligen-gui versions, I get this error upon generation:

```
ERROR:root:Failed to validate prompt for output 13:
ERROR:root:* GLIGENLoader 2:
ERROR:root:  - Value not in list: gligen_name: 'gligen_sd14_textbox_pruned.safetensors' not in []
ERROR:root:Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
```

Where these are my inputs:

![grafik](https://github.com/mut-ex/gligen-gui/assets/37689635/89bb6435-0ee8-4842-a50e-0cf8023524a4)

I downloaded and selected the model in the drop down and did everything as shown in the readme.
Could someone here point me in the right direction? Thanks already!

**Comment by YanWittmann** [comment]
Relevant node: https://github.com/comfyanonymous/ComfyUI/blob/5b40e7a5ed192e217575c55e061c17a52cf9a15d/nodes.py#L984

```python
class GLIGENLoader:
    @classmethod
    def INPUT_TYPES(s):
        return {"required": { "gligen_name": (folder_paths.get_filename_list("gligen"), )}}

    RETURN_TYPES = ("GLIGEN",)
    FUNCTION = "load_gligen"

    CATEGORY = "loaders"

    def load_gligen(self, gligen_name):
        gligen_path = folder_paths.get_full_path("gligen", gligen_name)
        gligen = comfy.sd.load_gligen(gligen_path)
        return (gligen,)
```

**Comment by mut-ex** [comment]
The GLIGEN model "gligen_sd14_textbox_pruned.safetensors" needs to go into the "ComfyUI/models/gligen" directory. It looks like you placed it instead in "ComfyUI/models/Stable-diffusion/GLIGEN".

The "checkpoint" section in the GUI is for specifying the Stable Diffusion 1.5 model you want to use.

**Comment by YanWittmann** [comment]
Ah, I see. If I do that though, the model is no longer present in the list of models to select from.
Inside of ComfyUI it can be selected via the gligen loader:

![grafik](https://github.com/mut-ex/gligen-gui/assets/37689635/302d6d34-499d-45ab-8a76-c74c093f520b)

**Comment by mut-ex** [comment]
Since there is only one GLIGEN model there isn't currently capability in the UI to select the GLIGEN model. It is just expected that you have the model in the ComfyUI/models/gligen directory. Then in the UI you select what checkpoint (not GLIGEN) you want to use e.g. Dreamshaper or Juggernaut etc

**Comment by YanWittmann** [comment]
Oh my god. I get it now.  
Thank you so much for your help, I got it to work:

![grafik](https://github.com/mut-ex/gligen-gui/assets/37689635/e04761cd-c847-4763-92f7-a2f29801b393)

I'm going to have a lot of fun with this!
